services:
  twodocker:
    build:
      context: Two
      dockerfile: Dockerfile
    ports:
      - 50051:50051

  onedocker:
    build:
      context: One
      dockerfile: Dockerfile
    ports:
      - 50051:50051
